### ISSUE TITLE
Scorm Version

### ISSUE THREAD

**Issue by ghost** [EscolaLMS/Scorm#32]
Does this support scorm version 1.2?

**Comment by qunabu** [comment]
@dyfero ☝️

**Comment by dyfero** [comment]
Yes, this package supports SCORM version 1.2.

**Comment by ghost** [comment]
> Yes, this package supports SCORM version 1.2.

I think 2004 3rd version is also implemented right? There seems to code for it too in "Scorm/test/API/ScormTrackApiTest.php"
I think the it should be mentioned as in the todo list I see in #1 that 1.2 and 2004 3rd noted as not implemented

**Comment by emanomary** [comment]
How can i use this package?
I installed it but i cannot know start point
